---
# tasks file for containerd

- name: Add kernel modules for containerd
  modprobe:
    name: "{{ item }}"
    state: present
  loop: 
    - overlay
    - br_netfilter

- name: Set sysctl for containerd installation
  sysctl:
    name: "{{ item }}"
    value: 1
    state: present
    reload: yes
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-ip6tables

- name: Update repositories cache and install packages for containerd
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - software-properties-common

- name: Add apt signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add containerd apt repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Update repositories cache and install containerd
  apt:
    name: containerd.io
    update_cache: yes
  notify:
    - Generate containerd config
    - Restart containerd
