---
# handlers file for cri-o

- name: Start cri-o
  systemd:
    state: started
    name: crio

- name: Restart kubelet
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet

- name: Restart cri-o
  systemd:
    state: restarted
    daemon_reload: yes
    name: crio