---
# tasks file for kubernetes/master

- name: Init Kubernetes cluster
  command: kubeadm init --token {{ kubeadm_token }} --pod-network-cidr={{ pod_network_cidr }}

- name: Creates directory for kube config
  file:
    path: /root/.kube
    state: directory

- name: Copy kube config for root user
  command: cp /etc/kubernetes/admin.conf /root/.kube/config