---
# handlers file for containerd

- name: Generate containerd config
  command: containerd config default > /etc/containerd/config.toml

- name: Restart containerd
  systemd:
    state: restarted
    name: containerd
