---
# tasks file for cri-o

- name: Add kernel modules for cri-o
  modprobe:
    name: "{{ item }}"
    state: present
  loop: 
    - overlay
    - br_netfilter
    
- name: Set sysctl for cri-o installation
  sysctl:
    name: "{{ item }}"
    value: 1
    state: present
    reload: yes
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-ip6tables

- name: Copy kubernetes.list file
  copy:
    src: 99-kubernetes-cri.conf
    dest: /etc/apt/sources.list.d/kubernetes.list

- name: Update repositories cache and install packages for cri-o
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - software-properties-common

- name: Add cri-o ppa repository
  apt_repository:
    repo: ppa:projectatomic/ppa

- name: Update repositories cache and install cri-o
  apt:
    name: cri-o-1.11
    update_cache: yes
  notify: Start cri-o