---
# tasks file for cri-o

- name: Copy sysctl file for runtime. Sysctl module does not work for this case
  copy: 
    src: 99-kubernetes-cri.conf
    dest: /etc/sysctl.d/99-kubernetes-cri.conf

- name: Run sysctl --system
  command: sysctl --system

- name: Update repositories cache and install packages for cri-o
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - software-properties-common

- name: Add cri-o ppa repository
  apt_repository:
    repo: ppa:projectatomic/ppa

- name: Update repositories cache and install cri-o
  apt:
    name: cri-o-1.11
    update_cache: yes
  notify: Start cri-o