---
# tasks file for cri-o

- name: Add kernel modules for cri-o
  modprobe:
    name: "{{ item }}"
    state: present
  loop: 
    - overlay
    - br_netfilter

- name: Set sysctl for cri-o installation
  sysctl:
    name: "{{ item }}"
    value: 1
    state: present
    reload: yes
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-ip6tables

- name: Update repositories cache and install packages for cri-o
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - software-properties-common

- name: Add cri-o ppa repository
  apt_repository:
    repo: ppa:projectatomic/ppa

- name: Update repositories cache and install cri-o
  apt:
    name: cri-o-1.15
    update_cache: yes
  notify: Start cri-o

- name: Copy configuration file for kubelet
  copy:
    src: kubelet
    dest: /etc/default/kubelet
  notify: Restart kubelet

- name: Symlinks fir cri-o | runc
  file:
    src: "/usr/lib/cri-o-runc/sbin/runc"
    dest: "/usr/bin/runc"
    state: link

- name: Symlinks fir cri-o | crio
  file:
    src: "/usr/lib/systemd/system/crio.service"
    dest: "/etc/systemd/system/crio.service"
    state: link

- name: Symlinks fir cri-o | crio-wipe
  file:
    src: "/usr/lib/systemd/system/crio-wipe.service"
    dest: "/etc/systemd/system/crio-wipe.service"
    state: link

- name: Copy configuration file for cri-o
  copy:
    src: crio.conf
    dest: /etc/crio/crio.conf
  notify: Restart cri-o

- name: Flush handlers to properly restart cri-o
  meta: flush_handlers